version: '3'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - mariadb
    environment:
      - DB_HOST=mariadb
      - DB_PORT=3306
      - DB_USERNAME=levelup
      - DB_PASSWORD=levelup
      - DB_DATABASE=levelup_docker
    env_file:
      - .env
    networks:
      - app-network

  mariadb:
    image: mariadb:10.5
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    env_file:
      - .env
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
